version: '3.4'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Secur3Passw0rd
    ports:
      - 5432:5432
    container_name: fastapi_example_db
    restart: always

  fastapi:
    image: fastapi-example
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    container_name: fastapi_example
    depends_on:
      - db
    restart: always
