on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  python-black:
    name: Format code with Black
    runs-on: ubuntu-latest
    steps:
      - name: Python Black format
        uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          src: "./"
